# PSchedulers Configuration
# 
# Tasks are defined in the 'tasks' section below.
# Each task has the following properties:
#   - command: The command to execute
#   - type: Type of schedule (INTERVAL, HOURLY, DAILY, WEEKLY)
#   - enabled: Whether the task should start automatically
#   - world, x, y, z: Optional location for region-specific tasks (Folia)
#   - conditions: Optional conditions for task execution
#     - min_players: Minimum number of players required (optional)
#     - max_players: Maximum number of players allowed (optional)
#
# Schedule type specific properties:
#   INTERVAL:
#     - interval: Number of ticks between executions (20 ticks = 1 second)
#   HOURLY:
#     - minute: Minute of each hour to execute (0-59)
#   DAILY:
#     - time: Time of day in HH:mm format
#   WEEKLY:
#     - days: List of days (MONDAY, TUESDAY, etc.)
#     - time: Time of day in HH:mm format

tasks:
  example_interval:
    command: "broadcast Hello World!"
    type: INTERVAL
    interval: 6000  # 5 minutes
    enabled: false
    conditions:
      min_players: 5  # Only execute when 5 or more players are online

  example_hourly:
    command: "broadcast It's a new hour!"
    type: HOURLY
    minute: 0  # Execute at the start of each hour
    enabled: false
    conditions:
      max_players: 10  # Only execute when 10 or fewer players are online

  example_daily:
    command: "broadcast Good morning!"
    type: DAILY
    time: "09:00"  # Execute at 9 AM
    enabled: false
    conditions:
      min_players: 1  # Only execute when at least 1 player is online
      max_players: 50  # And no more than 50 players

  example_weekly:
    command: "broadcast Weekly maintenance in 1 hour!"
    type: WEEKLY
    days: [MONDAY, WEDNESDAY, FRIDAY]
    time: "20:00"  # Execute at 8 PM
    enabled: false 